# Required
version: 2

# Image to use
build:
  os: ubuntu-20.04  # <- add this line
  tools:
    python: "3.10"
  image: testing

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
